// test_vue/src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <router-link class="navbar-brand" to="/">
        <img src="/GFC-logo.png" alt="GFC Logo" height="30" class="d-inline-block align-text-top me-2">
        GFC
      </router-link>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto" v-if="user">
          <li class="nav-item">
            <router-link class="nav-link" to="/ranking">Ranking</router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" to="/concursos">Concursos</router-link>
          </li>
          <li class="nav-item" v-if="isDelegadoOrAdmin">
            <router-link class="nav-link" to="/usuarios">{{ getNombreUsuarios }}</router-link>
          </li>
          <li class="nav-item" v-if="isAdmin">
            <router-link class="nav-link" to="/organizaciones">Organizaciones</router-link>
          </li>
        </ul>
        
        <ul class="navbar-nav" v-if="user">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
              <img :src="user.avatar || '/default-avatar.png'" alt="Avatar" class="rounded-circle me-1" width="24" height="24">
              {{ user.first_name }} {{ user.last_name }}
            </a>
            <ul class="dropdown-menu">
              <li>
                <router-link class="dropdown-item" :to="`/perfil/${user.id}`">
                  <i class="bi bi-person"></i> Mi Perfil
                </router-link>
              </li>
              <li>
                <router-link class="dropdown-item" to="/perfil/editar">
                  <i class="bi bi-gear"></i> Configuración
                </router-link>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item" href="#" @click.prevent="logout">
                  <i class="bi bi-box-arrow-right"></i> Cerrar Sesión
                </a>
              </li>
            </ul>
          </li>
        </ul>
        
        <ul class="navbar-nav" v-else>
          <li class="nav-item">
            <router-link class="nav-link" to="/login">Iniciar Sesión</router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" to="/registro">Registrarse</router-link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import authService from '../services/auth.js'
import rolificadorService from '../services/rolificador.js'

export default {
  name: 'NavBar',
  data() {
    return {
      user: null,
      authInterval: null
    }
  },
  computed: {
    isAdmin() {
      return rolificadorService.isAdmin(this.user)
    },
    isDelegadoOrAdmin() {
      return rolificadorService.esDelegado(this.user) || rolificadorService.isAdmin(this.user)
    },
    getNombreUsuarios() {
      return rolificadorService.getNombreUsuarios(this.user?.role_id)
    }
  },
  async mounted() {
    await this.loadUser()
    // Verificar autenticación periódicamente (similar a Angular)
    this.authInterval = setInterval(async () => {
      if (authService.isLoggedIn() && !this.user) {
        await this.loadUser()
      } else if (!authService.isLoggedIn() && this.user) {
        this.user = null
      }
    }, 1000)
  },
  beforeUnmount() {
    if (this.authInterval) {
      clearInterval(this.authInterval)
    }
  },
  methods: {
    async loadUser() {
      this.user = await authService.getUser()
    },
    async logout() {
      await authService.logout()
      this.$router.push('/login')
    }
  }
}
</script>

<style scoped>
.navbar-brand img {
  filter: brightness(0) invert(1);
}

.dropdown-item i {
  margin-right: 0.5rem;
}
</style>

// angular/src/app/nav/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { MenuController } from '@ionic/angular';
import { PopoverController } from '@ionic/angular';

import { UsuarioPage } from '../../usuario/usuario.page';
import { NavigationEnd, Router } from '@angular/router';
import { AuthService } from 'src/app/modules/auth/services/auth.service';
import { RolificadorService } from 'src/app/modules/auth/services/rolificador.service';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent implements OnInit {

  currentUrl: string = '';

  constructor(
    private menu: MenuController,
    public popoverController: PopoverController,
    public router: Router,
    public auth: AuthService,
    public rolificador: RolificadorService
  ) { }

  ngOnInit() {
    this.currentUrl = this.router.url;
    this.router.events
      .pipe(filter(e => e instanceof NavigationEnd))
      .subscribe((e) => {
        this.currentUrl = this.router.url;
      });
  }

  isActive(url: string): boolean {
    if (this.currentUrl === url) return true;
    if (url === '/concursos') {
      return this.currentUrl.startsWith('/concursos/') && !this.currentUrl.startsWith('/concursos/ranking');
    }
    return this.currentUrl.startsWith(url + '/') || this.currentUrl.startsWith(url + '?');
  }

  async openPopover(ev: any, ctrl: any, url: string) {
    const popover = await this.popoverController.create({
      component: ctrl,
      cssClass: 'my-custom-class',
      event: ev,
      translucent: true,
    });
    await popover.present();
    this.router.events
      .pipe()
      .subscribe((e) => {
        if (e instanceof NavigationEnd) {
          popover.dismiss();
        }
      });
    await popover.onDidDismiss();
  }

  async mostrarPerfil(ev: any) {
    this.openPopover(ev, UsuarioPage, '/perfil/editar');
  }

  toggleMenu() {
    this.menu.toggle();
  }

}

<nav class="navbar navbar-expand-lg navbar-light bg-light px-3 fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center gap-2 clickeable" [routerLink]="['/']">
      <img src="../../../assets/gfc-logo.png" alt="GFC" width="30" height="30" class="d-inline-block align-text-top">
      <span class="d-none d-lg-inline">Grupo Fotográfico Centro</span>
    </a>

    <div class="d-flex align-items-center gap-1 ms-auto">
      <div class="d-none d-lg-flex gap-1" *ngIf="auth.loggedIn && auth.user | async as u">
        <a class="btn btn-outline-dark btn-sm" [class.active-link]="isActive('/herramientas')" *ngIf="rolificador.isAdmin(u) || rolificador.esDelegado(u)" [routerLink]="['/herramientas']">Herramientas</a>
        <a class="btn btn-outline-dark btn-sm" [class.active-link]="isActive('/concursos/ranking')" [routerLink]="['/concursos/ranking']">Ranking</a>
        <a class="btn btn-outline-dark btn-sm" [class.active-link]="isActive('/concursos')" [routerLink]="['/concursos']">Concursos</a>
        <a class="btn btn-outline-dark btn-sm" [class.active-link]="isActive('/usuarios')" *ngIf="rolificador.esDelegado(u) || rolificador.isAdmin(u)" [routerLink]="['/usuarios']">
          {{ rolificador.getNombreUsuarios(u.role_id) }}
        </a>
        <a class="btn btn-outline-dark btn-sm" [class.active-link]="isActive('/organizaciones')" *ngIf="rolificador.isAdmin(u)" [routerLink]="['/organizaciones']">Organizaciones</a>
      </div>

      <ng-container *ngIf="auth.loggedIn; else login">
        <button class="btn btn-outline-dark" (click)="mostrarPerfil($event)">
          <i class="bi bi-person-circle fs-5"></i>
        </button>
        <button class="btn btn-outline-dark d-lg-none" (click)="toggleMenu()">
          <i class="bi bi-list fs-5"></i>
        </button>
      </ng-container>

      <ng-template #login>
        <a class="btn btn-outline-dark" *ngIf="router.url != '/login'" [routerLink]="['/login']">Ingresar</a>
      </ng-template>
    </div>
  </div>
</nav>
